accounts/urls.py
from django.urls import path
from accounts.views import SignUpFormView


app_name = 'accounts'

urlpatterns = [
    path('sign-up/', SignUpFormView.as_view(), name='sign-up')
]

main/urls.py
from django.urls import path
from . import views
from .views import Home, ArticleListView, ArticleDetailView, ArticleUpdateView

app_name = 'main'

urlpatterns = [
    # Articles
    path('', Home.as_view(), name='home'),
    path('articles', ArticleListView.as_view(), name='article-list'),
    path('articles/<uuid:pk>', ArticleDetailView.as_view(), name="article-detail"),
    path('articles/<uuid:pk>/update',
         ArticleUpdateView.as_view(), name="article-update"),
]

website/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('', include('django.contrib.auth.urls')),
    path('', include('accounts.urls')),
] 

accounts/models.py
# Create your models here.
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.utils.translation import gettext_lazy as _
import uuid
from datetime import date
# Create your models here.
from django.contrib.auth.base_user import BaseUserManager
from django.core.exceptions import ValidationError
from . import validators

class CIEmailField(models.EmailField):
    """
    Override EmailField to convert emails to lowercase before saving.
    """

    def to_python(self, value):
        """
        Convert email to lowercase.
        """
        value = super(CIEmailField, self).to_python(value)
        return value.lower()


class UserManager(BaseUserManager):
    use_in_migrations = True

    def _create_user(self, email, password, **extra_fields):
        if not email:
            raise ValueError('Users require an email field')
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email, password, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')

        return self._create_user(email, password, **extra_fields)


class User(AbstractUser):
    username = None
    email = CIEmailField(_('email address'), unique=True)
    national_id = models.CharField(max_length=10, validators=[
                                   validators.NationalIdValidator()])
    name = models.CharField(max_length=150)
    phone_number = models.CharField(max_length=10, validators=[
        validators.PhoneNumberValidator()])
    date_of_birth = models.DateField(null=True, blank=True)

    def clean(self):
        if self.date_of_birth and self.date_of_birth > date.today():
            raise ValidationError({'date_of_birth':"The date can't be in the feature"})
        return super().clean()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    objects = UserManager()

main/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.utils.translation import gettext_lazy as _
import uuid

# Create your models here.
from django.contrib.auth.base_user import BaseUserManager
from accounts.models import User


class Article(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    title = models.CharField(max_length=255, blank=True, null=True)
    author = models.CharField(max_length=255, blank=True, null=True)
    content = models.CharField(max_length=500, blank=True, null=True)
    description = models.CharField(max_length=500, blank=True, null=True)
    published_at= models.DateTimeField(blank=True, null=True)
    url_to_image = models.ImageField(upload_to='gallery', max_length=800)
    favorites = models.ManyToManyField(
        User, related_name='favorites', default=None, blank=True)

    def __str__(self):
        return self.title

accounts/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm



class RegistrationForm(UserCreationForm):
    date_of_birth = forms.DateField(required=True, label='Date of Birth',
                                    widget=forms.DateInput(attrs={
                                        'placeholder': 'Birth Date',
                                        'class': 'form-control',
                                        'type': 'date',
                                    }))

    class Meta:
        model = get_user_model()
        fields = ['name', 'email', 'national_id', 'phone_number', 'date_of_birth',
                  'password1', 'password2']

accounts/views.py
from django.views.generic import CreateView
from .forms import RegistrationForm
from django.urls import reverse_lazy

# Create your views here.


class SignUpFormView(CreateView):
    form_class = RegistrationForm
    success_url = reverse_lazy('login')
    template_name = 'registration/sign_up.html'

main/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login
from main.models import Article
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404
from django.http import HttpResponseRedirect
from django.views.generic import ListView, TemplateView, DetailView, UpdateView, CreateView, RedirectView
from django.utils.decorators import method_decorator
from django.urls import reverse_lazy
from accounts.forms import RegistrationForm
from django.contrib import messages


class Home(RedirectView):
    pattern_name = 'main:article-list'


class ArticleListView(ListView):
    model = Article
    paginate_by = 6

    def get_queryset(self):
        articles = super().get_queryset()
        if self.request.GET.get('sub', None) == 'favorites':
            articles = articles.filter(favorites__id=self.request.user.id)
        return articles


class ArticleDetailView(DetailView):
    model = Article
    is_favorite = bool

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(**kwargs)
        context['is_favorite'] = False

        if self.object.favorites.filter(id=self.request.user.id).exists():
            context['is_favorite'] = True

        return context


@method_decorator(login_required, name='dispatch')
class ArticleUpdateView(UpdateView):
    model = Article
    fields = ['favorites']

    def get_success_url(self):
        return reverse_lazy('main:article-detail', args=[self.object.pk])

    def form_valid(self, form):
        if self.object.favorites.filter(id=self.request.user.id).exists():
            self.object.favorites.remove(self.request.user)
            messages.success(self.request, "The article has been removed successfully")

        else:
            self.object.favorites.add(self.request.user)
            messages.success(self.request, "The article has been added successfully")

        form.cleaned_data['favorites'] = self.object.favorites.all()
        return super().form_valid(form)

main/templates/main/article_detail.html
{% extends 'main/base.html' %} {% block title %} Home Page {% endblock %} {% load static %} {%block content %}

<div class="container">
    <br><br>
    <div class="mb-2 d-flex justify-content-end">
        <div>
            </span> {% if user.is_authenticated %}
            <form method="post" action={% url 'main:article-update' article.id %}>
                {% csrf_token %} {%if is_favorite%}
                <button class="btn btn-danger" type="submit">
                    <span class="fa fa-heart"></span>
              Remove from favorite
            </button> {%else%}

                <button class="btn btn-outline-danger" type="submit">
                    <span class="fa fa-heart"></span>
                    Add to favorite
            </button> {% endif %}
            </form>
            {% endif %}
        </div>
    </div>
    <div class="row">
        <div class="col-md-5">
            <br>
            <img class="img-fluid" src="{{ article.url_to_image }}" alt="" style="width: 90%;">
            <div class="mt-2">
                <div>
                    <span class="card-title">
                                <strong>Author:</strong>
                                {{article.author}}</span>

                </div>
                <div>
                    <span>
                                <strong>Published At:</strong>
                               {{article.published_at}}</span>
                </div>

            </div>
        </div>
        <div class="col-md-7 shadow-lg p-3 mb-5 bg-white rounded">
            <h1 class="my-3">{{ article.title }}</h1>
            <p class="lead mt-5">{{ article.content }}</p>
        </div>
    </div>
</div>

{% endblock content %}

main/templates/main/article_list.html
{% extends 'main/base.html' %} {% block title %} Home Page {% endblock %} {% load static %} {%block content %}


<div class="row">
    <!--ADD CLASSES HERE d-flex align-items-stretch-->
    {% for article in object_list %}
    <div class="col-lg-4 mb-3 d-flex align-items-stretch">
        <div class="card">
            <img src="{{ article.url_to_image }}" class="card-img-top" alt="Card Image">
            <div class="card-body d-flex flex-column">
                <h5 class="card-title">{{ article.title }}</h5>
                <p class="card-text mb-4">{{ article.description }}</p>
                <a href="{% url 'main:article-detail' article.id %}" class="btn btn-primary text-white mt-auto align-self-start">Read More</a>
            </div>
        </div>
    </div>
    {% empty %} {% if user.is_authenticated and request.GET.sub %}
    <div class="alert alert-info" role="alert">
        You have no favorites!
    </div>

    {% else %}
    <div class="alert alert-info" role="alert">
        There is no news yet, but keep checking in :)
    </div>
    {% endif %} {% endfor %}
</div>

{% if page_obj %}
<nav>
    <ul class="pagination justify-content-center">
        {% if page_obj.has_previous %}
        <li class="page-item">
            <a class="page-link" href="{% if request.GET.sub == 'favorites' %}?page={{ page_obj.previous_page_number }}&sub=favorites {% else %}?page={{ page_obj.previous_page_number }} {% endif %}">Previous</a >
    </li>
    {% endif %} {% for page_number in page_obj.paginator.page_range %}
    <li
      class="page-item {% if page_obj.number == page_number %} active  {% endif %}"
    >
      <a class="page-link" href="{% if request.GET.sub == 'favorites' %}?page={{ page_number }}&sub=favorites {% else %} ?page={{ page_number }} {% endif %}">{{ page_number }}</a>
        </li>
        {%endfor%} {% if page_obj.has_next %}
        <li class="page-item">
            <a class="page-link" href="{% if request.GET.sub == 'favorites' %}?page={{ page_obj.next_page_number }}&sub=favorites  {% else %}?page={{ page_obj.next_page_number }} {% endif %}">Next</a>
        </li>
        {% endif %}
    </ul>
</nav>
{% endif %} {% endblock content %}

main/templates/main/base.html
<!DOCTYPE html>
<html lang="en" class="h-100">

<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />


    <!-- CSS only -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous" />
    <!-- CSS -->
    <link rel="stylesheet" href="//cdn.jsdelivr.net/npm/alertifyjs@1.13.1/build/css/alertify.min.css" />
    <!-- Default theme -->
    <link rel="stylesheet" href="//cdn.jsdelivr.net/npm/alertifyjs@1.13.1/build/css/themes/default.min.css" />
    <title>{% block title %}my site {% endblock %}</title>

    <body class="d-flex flex-column h-100">

        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container-fluid">
                <div>
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a {% if request.GET.sub != 'favorites' %}class="nav-link active" {% else %} class="nav-link" {% endif %} href="{% url 'main:article-list' %}">News</a>
                        </li>
                        {% if user.is_authenticated %}
                        <li class="nav-item">
                            <a {% if request.GET.sub == 'favorites' %}class="nav-link active" {% else %} class="nav-link" {% endif %} href="{% url 'main:article-list' %}?sub=favorites">My Favorite</a>
                        </li>
                        {%endif%}
                    </ul>
                </div>
                <div>
                    <ul class="navbar-nav">
                        {% if user.is_authenticated %}
                        <span class="navbar-text">Logged in as {{user.email}} | </span>
                        <li class="nav-item">
                            <a class="nav-link" href="/logout">Logout</a>
                        </li>
                        {% else %}
                        <li class="nav-item">
                            <a class="nav-link" href="/login">Login</a>
                        </li>
                        {%endif%}
                    </ul>
                </div>
            </div>
        </nav>

        <div class="mt-5 container">
            {% block content %} {% endblock %}
        </div>

        <footer class="footer mt-auto text-center text-lg-start bg-light text-muted">
            <div class="text-center p-4" style="background-color: rgba(0, 0, 0, 0.05);">
                © 2022:
                <a class="text-reset fw-bold" href="{% url 'main:article-list' %}">NewsWebsite.com</a>
            </div>
        </footer>


        <!-- JavaScript Bundle with Popper -->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous">
        </script>
        <script src="//cdn.jsdelivr.net/npm/alertifyjs@1.13.1/build/alertify.min.js"></script>
        <script src="http://code.jquery.com/jquery-1.9.1.min.js"></script>

        <script>
           {% for message in messages %}
            alertify.set('notifier', 'position', 'top-center');
            alertify.success('{{message}}');
            {% endfor %}
        </script>
    </body>

</html>